"""Initial

Revision ID: 0.1
Revises:
Create Date: 2024-02-07 12:28:15.360022

"""
from typing import Sequence, Union

from sqlalchemy import text
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0.1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # Создаем схему

    op.execute(text('CREATE SCHEMA IF NOT EXISTS lcard'))

    # Добавляем расширение GUID4
    op.execute(text('CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;'))

    op.execute(text('''
    CREATE OR REPLACE FUNCTION public.uuid_generate_v4()
    RETURNS uuid
    LANGUAGE 'c'
    COST 1
    VOLATILE STRICT PARALLEL SAFE
    AS '$libdir/uuid-ossp', 'uuid_generate_v4';
    '''))


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
