"""init

Revision ID: 0.2
Revises: 
Create Date: 2024-02-07 15:58:44.987457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0.2'
down_revision: Union[str, None] = '0.1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('money_certificate_payment',
    sa.Column('id', sa.TEXT(), server_default=sa.text('public.uuid_generate_v4()'), nullable=False),
    sa.Column('created_utc', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_utc', sa.TIMESTAMP(), nullable=True),
    sa.Column('pnvl_order_number', sa.TEXT(), nullable=True, comment='Номер приказа стажа службы для ПНВЛ'),
    sa.Column('pnvl_order_date', sa.Date(), nullable=True, comment='От какой даты приказ'),
    sa.Column('pnvl_date', sa.Date(), nullable=True, comment='На какую дату актуальна информация'),
    sa.Column('pnvl_experience', sa.TEXT(), nullable=True, comment='Стаж службы. (Прим. дни-месяц-год)'),
    sa.Column('pnvl_percentage', sa.Float(), nullable=True, comment='Процент надбавки за выслугу лет'),
    sa.Column('pnvl_sum', sa.Float(), nullable=True, comment='Сумма надбавки за выслугу лет'),
    sa.Column('position_salary', sa.Float(), nullable=True, comment='Оклад по воинской должности'),
    sa.Column('rank_salary', sa.Float(), nullable=True, comment='Оклад по воинскому званию'),
    sa.Column('ouvs_order_number', sa.TEXT(), nullable=True, comment='Номер приказа надбавки за ОУВС'),
    sa.Column('ouvs_order_date', sa.Date(), nullable=True, comment='Дата приказа надбавки за ОУВС'),
    sa.Column('ouvs_percentage', sa.Float(), nullable=True, comment='Процент надбавки за ОУВС'),
    sa.Column('ouvs_sum', sa.Float(), nullable=True, comment='Сумма надбавки за ОУВС'),
    sa.Column('ouvs_is_active', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False, comment='Активна ли надбавка'),
    sa.Column('admission_form_order_number', sa.TEXT(), nullable=True, comment='Номер приказа надбавки за секретность'),
    sa.Column('admission_form_order_date', sa.Date(), nullable=True, comment='Дата приказа надбавки за секретность'),
    sa.Column('admission_form_percentage', sa.Float(), nullable=True, comment='Процент надбавки за секретность'),
    sa.Column('admission_form_sum', sa.Float(), nullable=True, comment='Сумма надбавки за секретность'),
    sa.Column('admission_form_is_active', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False, comment='Активна ли надбавка'),
    sa.Column('award_order_number', sa.TEXT(), nullable=True, comment='Номер приказа на премию'),
    sa.Column('award_order_date', sa.Date(), nullable=True, comment='Дата приказа на премию'),
    sa.Column('award_percentage', sa.Float(), nullable=True, comment='Процент премии'),
    sa.Column('award_sum', sa.Float(), nullable=True, comment='Сумма надбавки'),
    sa.Column('award_is_active', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False, comment='Активна ли надбавка'),
    sa.Column('qualification_order_number', sa.TEXT(), nullable=True, comment='Номер приказа надбавки за кл. квалификацию'),
    sa.Column('qualification_order_date', sa.Date(), nullable=True, comment='Дата приказа надбавки за кл. квалификацию'),
    sa.Column('qualification_percentage', sa.Float(), nullable=True, comment='Процент надбавки за кл. квалификацию'),
    sa.Column('qualification_sum', sa.Float(), nullable=True, comment='Сумма надбавки за кл. квалификацию.'),
    sa.Column('primary_premium_order_name', sa.TEXT(), nullable=True, comment='Наименование надбавки'),
    sa.Column('qualification_is_active', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False, comment='Активна ли надбавка'),
    sa.Column('primary_premium_order_number', sa.TEXT(), nullable=True, comment='Номер приказа надбавки'),
    sa.Column('primary_premium_order_date', sa.Date(), nullable=True, comment='Дата приказа надбавки'),
    sa.Column('primary_premium_percentage', sa.Float(), nullable=True, comment='Процент надбавки'),
    sa.Column('primary_premium_sum', sa.Float(), nullable=True, comment='Сумма надбавки'),
    sa.Column('primary_premium_is_active', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False, comment='Активна ли надбавка'),
    sa.Column('secondary_premium_order_name', sa.TEXT(), nullable=True, comment='Наименования надбавки'),
    sa.Column('secondary_premium_order_number', sa.TEXT(), nullable=True, comment='Номер приказа надбавки'),
    sa.Column('secondary_premium_order_date', sa.Date(), nullable=True, comment='Дата приказа надбавки'),
    sa.Column('secondary_premium_percentage', sa.Float(), nullable=True, comment='Процент надбавки'),
    sa.Column('secondary_premium_sum', sa.Float(), nullable=True, comment='Сумма надбавки'),
    sa.Column('secondary_premium_is_active', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False, comment='Активна ли надбавка'),
    sa.Column('total_salary', sa.Float(), nullable=True, comment='Всего начислено'),
    sa.Column('total_salary_date', sa.Date(), nullable=True, comment='С какого числа начислено'),
    sa.Column('payment_status', sa.BOOLEAN(), server_default=sa.text('false'), nullable=True, comment='Заполнены ли данные для выплаты полностью.'),
    sa.PrimaryKeyConstraint('id'),
    schema='lcard'
    )
    op.create_table('position_salary',
    sa.Column('id', sa.TEXT(), server_default=sa.text('public.uuid_generate_v4()'), nullable=False),
    sa.Column('created_utc', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_utc', sa.TIMESTAMP(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False, comment='Тарифный разряд'),
    sa.Column('value', sa.Float(), nullable=False, comment='Размер оклада по тарифному разряду'),
    sa.Column('sort', sa.Integer(), autoincrement=True, nullable=False, comment='Сортировка'),
    sa.Column('isActive', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False, comment='Статус классификатора'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='lcard'
    )
    op.create_table('rank_salary',
    sa.Column('id', sa.TEXT(), server_default=sa.text('public.uuid_generate_v4()'), nullable=False),
    sa.Column('created_utc', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_utc', sa.TIMESTAMP(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False, comment='Воинское звание'),
    sa.Column('value', sa.Float(), nullable=False, comment='Размер оклада по воинскому званию'),
    sa.Column('sort', sa.Integer(), autoincrement=True, nullable=False, comment='Сортировка'),
    sa.Column('isActive', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False, comment='Статус классификатора'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='lcard'
    )
    op.create_table('reporting_period',
    sa.Column('id', sa.TEXT(), server_default=sa.text('public.uuid_generate_v4()'), nullable=False),
    sa.Column('created_utc', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_utc', sa.TIMESTAMP(), nullable=True),
    sa.Column('value', sa.TEXT(), nullable=False, comment='Отчетный период (Прим. 2024-2025)'),
    sa.Column('sort', sa.Integer(), autoincrement=True, nullable=False, comment='Сортировка'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value'),
    schema='lcard'
    )
    op.create_table('money_certificate',
    sa.Column('id', sa.TEXT(), server_default=sa.text('public.uuid_generate_v4()'), nullable=False),
    sa.Column('created_utc', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_utc', sa.TIMESTAMP(), nullable=True),
    sa.Column('certificate_number', sa.TEXT(), nullable=True, comment='Номер карточки денежного довольствия'),
    sa.Column('certificate_date', sa.Date(), nullable=True, comment='От какой даты денежный аттестат'),
    sa.Column('certificate_expire_date', sa.Date(), nullable=True, comment='По какое число удовлетворение аттестатом'),
    sa.Column('year_first', sa.TEXT(), nullable=True, comment='Выплата за первый год отчетного периода'),
    sa.Column('year_second', sa.TEXT(), nullable=True, comment='Выплата за второй год отчетного периода'),
    sa.Column('card_author', sa.TEXT(), nullable=True, comment='Составил карточки'),
    sa.Column('card_inspector', sa.TEXT(), nullable=True, comment='Проверяющий карточки'),
    sa.ForeignKeyConstraint(['year_first'], ['lcard.money_certificate_payment.id'], ),
    sa.ForeignKeyConstraint(['year_second'], ['lcard.money_certificate_payment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_first'),
    sa.UniqueConstraint('year_second'),
    schema='lcard'
    )
    op.create_table('person',
    sa.Column('id', sa.TEXT(), server_default=sa.text('public.uuid_generate_v4()'), nullable=False),
    sa.Column('created_utc', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_utc', sa.TIMESTAMP(), nullable=True),
    sa.Column('firstname', sa.TEXT(), nullable=False, comment='Имя'),
    sa.Column('middlename', sa.TEXT(), nullable=False, comment='Отчество'),
    sa.Column('lastname', sa.TEXT(), nullable=False, comment='Фамилия'),
    sa.Column('birthday', sa.Date(), nullable=False, comment='День рождения'),
    sa.Column('personal_number', sa.TEXT(), nullable=True, comment='Личный номер'),
    sa.Column('tariff_category', sa.TEXT(), nullable=True, comment='Тарифный разряд'),
    sa.Column('job_rank', sa.TEXT(), nullable=True, comment='Воинское звание'),
    sa.Column('job_position', sa.TEXT(), nullable=True, comment='Должность'),
    sa.Column('job_position_order_entry_number', sa.TEXT(), nullable=True, comment='Номер приказа о вступление в должность'),
    sa.Column('job_position_order_entry_date', sa.Date(), nullable=True, comment='Дата приказа о вступление в должность'),
    sa.Column('job_position_order_appointment_number', sa.TEXT(), nullable=True, comment='Номер приказа о назначение на должность'),
    sa.Column('job_position_order_appointment_date', sa.Date(), nullable=True, comment='Дата приказа о назначение на должность'),
    sa.Column('vus', sa.TEXT(), nullable=True, comment='ВУС'),
    sa.Column('unit', sa.TEXT(), nullable=True, comment='Подразделение'),
    sa.Column('inn', sa.TEXT(), nullable=True, comment='ИНН'),
    sa.Column('arrived_from', sa.TEXT(), nullable=True, comment='Откуда прибыл'),
    sa.Column('isActive', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False, comment='Статус военнослужащего'),
    sa.ForeignKeyConstraint(['job_rank'], ['lcard.rank_salary.id'], ),
    sa.ForeignKeyConstraint(['tariff_category'], ['lcard.position_salary.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='lcard'
    )
    op.create_table('money_certificate_relation',
    sa.Column('id', sa.TEXT(), server_default=sa.text('public.uuid_generate_v4()'), nullable=False),
    sa.Column('created_utc', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_utc', sa.TIMESTAMP(), nullable=True),
    sa.Column('person', sa.TEXT(), nullable=False, comment='Идентификатор персоны'),
    sa.Column('money_certificate', sa.TEXT(), nullable=False, comment='Идентификатор карточки денежного довольствия'),
    sa.Column('reporting_period', sa.TEXT(), nullable=False, comment='Идентификатор периода'),
    sa.ForeignKeyConstraint(['money_certificate'], ['lcard.money_certificate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person'], ['lcard.person.id'], ),
    sa.ForeignKeyConstraint(['reporting_period'], ['lcard.reporting_period.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='lcard'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('money_certificate_relation', schema='lcard')
    op.drop_table('person', schema='lcard')
    op.drop_table('money_certificate', schema='lcard')
    op.drop_table('reporting_period', schema='lcard')
    op.drop_table('rank_salary', schema='lcard')
    op.drop_table('position_salary', schema='lcard')
    op.drop_table('money_certificate_payment', schema='lcard')
    # ### end Alembic commands ###
