"""Initial

Revision ID: 0.3
Revises:
Create Date: 2024-02-07 12:28:15.360022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0.3'
down_revision: Union[str, None] = '0.2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Заполнение окладов по воинским званиям
    op.execute("""
        INSERT INTO lcard.rank_salary (id, name, value, sort) VALUES ('4585dc1a-fbac-47f0-b13b-f87ff6779851', 'рядовой', 6026, 0);
        INSERT INTO lcard.rank_salary (id, name, value, sort) VALUES ('7e8a3461-8265-440b-9355-040472d633f7', 'ефрейтор', 6628, 1);
        INSERT INTO lcard.rank_salary (id, name, value, sort) VALUES ('d503ce60-6847-44cb-95a4-99008731bc77', 'младший сержант', 7233, 2);
        INSERT INTO lcard.rank_salary (id, name, value, sort) VALUES ('a0a10443-1aef-4ad4-bdb5-0364abb39039', 'сержант', 7834, 3);
        INSERT INTO lcard.rank_salary (id, name, value, sort) VALUES ('78f53bf0-a377-4338-b7fe-c251ba35a5b7', 'старший сержант', 8437, 4);
        INSERT INTO lcard.rank_salary (id, name, value, sort) VALUES ('dbc1f287-5055-4dbe-b465-49827b8162cc', 'старшина', 9040, 5);
        INSERT INTO lcard.rank_salary (id, name, value, sort) VALUES ('03642719-8c1d-4edd-b4a9-295fe48e5fc5', 'прапорщик', 9641, 6);
        INSERT INTO lcard.rank_salary (id, name, value, sort) VALUES ('097a6208-c96a-40d5-ba75-3c72f07101dc', 'старший прапорщик', 10244, 7);
        INSERT INTO lcard.rank_salary (id, name, value, sort) VALUES ('330ed7a3-6f63-4604-af5b-3a7e0bde4070', 'младший лейтенант', 11449, 8);
        INSERT INTO lcard.rank_salary (id, name, value, sort) VALUES ('2c6c9c4a-390b-4c3f-b2ba-cb539854f61e', 'лейтенант', 12052, 9);
        INSERT INTO lcard.rank_salary (id, name, value, sort) VALUES ('2f1c6a09-459a-4fa5-9f9c-2e51f16f8790', 'старший лейтенант', 12654, 10);
        INSERT INTO lcard.rank_salary (id, name, value, sort) VALUES ('0988c549-0ab2-4efe-83e8-c9a2cd085ad4', 'капитан', 13255, 11);
        INSERT INTO lcard.rank_salary (id, name, value, sort) VALUES ('2354052f-f9ff-4f4c-9e89-d57ec05c183b', 'майор', 13860, 12);
        INSERT INTO lcard.rank_salary (id, name, value, sort) VALUES ('74d2c274-f4bd-4036-8352-39c3070c9188', 'подполковник', 14462, 13);
        INSERT INTO lcard.rank_salary (id, name, value, sort) VALUES ('0cc8d9a8-741e-4af2-aa8e-48969dfa2a44', 'полковник', 15667, 14);
    """)

    # Заполнение окладов по воинским должностям
    op.execute("""
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('c6444fde-69b1-41b4-bbeb-df20007f94b4', 1, 12052, 0);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('e762bf5c-d926-48ae-ab02-85cbecdc2868', 2, 13255, 1);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('164f515a-2b3c-4bdf-a392-a7d6ea8308b5', 3, 14462, 2);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('e1fc9dca-4160-42a4-b20e-805dab5946a4', 4, 15667, 3);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('3f157e22-70b0-41f3-907f-46f270ec8565', 5, 18077, 4);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('23ff4c01-3ba6-4d2b-9cd9-b0f6fe1e1c2b', 6, 19281, 5);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('ab5c283c-3059-422b-ba20-768341be8a10', 7, 20486, 6);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('0948ccf8-7dbf-4e97-a849-f1e74a4fb742', 8, 21089, 7);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('362beebc-f085-4fd6-8e13-f039734af1fb', 9, 21691, 8);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('9c1219bb-501e-46e0-9ce3-8bcd7fb8b671', 10, 24100, 9);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('b1a6afea-0d1e-4f92-ab18-bf7c0dc68c92', 11, 24704, 10);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('e0e9d67e-46a5-4888-ac23-cd752bbdcac4', 12, 25307, 11);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('f3040af9-ab32-4eab-b8cd-ca8ce8cc10ea', 13, 25908, 12);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('61a27a7d-bd62-4ff3-b9df-8618c8d11a04', 14, 26510, 13);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('39fb5c23-eaf6-43e6-a678-9dcc420ae849', 15, 27114, 14);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('e7a75db9-63ec-408f-b43b-5ed97c8f9667', 16, 27715, 15);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('e25a10bf-f799-40f9-90b7-58737d3c7767', 17, 28318, 16);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('a23114a7-5168-425f-b68d-8a2cb25dda7b', 18, 28922, 17);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('f94e8a89-f8d9-4cb9-a436-8afa8db40000', 19, 29523, 18);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('cfc482c6-61a0-4e27-bec4-962c92ba3cb4', 20, 30125, 19);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('633437b0-1f64-45f0-96dc-4eb34baa5bcc', 21, 30728, 20);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('8f9696bf-33f3-49f8-a381-e73ce79b9a38', 22, 30728, 21);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('defd8b3c-000a-4df6-9c02-eb1e7859146e', 23, 30728, 22);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('b6f79a88-296d-4fc1-8345-c086e792b8b6', 24, 30728, 23);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('6a791106-dc2b-47c9-a320-bed5e0fe4566', 25, 30728, 24);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('449b4aed-1ec3-4ace-a697-308d4a9bdfeb', 26, 30728, 25);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('aa5f4211-dc67-439f-9bb7-58adb7a83c34', 27, 30728, 26);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('8a6d6aea-5f45-4134-b926-0bfcc2aa017c', 28, 30728, 27);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('7d08fa7c-dafb-47cf-a4c2-5fa52f30dfbd', 29, 30728, 28);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('73f8f406-1929-42c4-a2e6-6bd252f2a2e9', 30, 30728, 29);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('fcad0392-f699-4257-a68a-c6289235bde6', 31, 30728, 30);
        INSERT INTO lcard.position_salary (id, name, value, sort) VALUES ('f204f715-8543-4acd-bbc5-6abde40fa4ee', 32, 30728, 31);
    """)

    # Заполнение персон

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""TRUNCATE lcard.rank_salary CASCADE;""")
    op.execute("""TRUNCATE lcard.position_salary CASCADE;""")
    pass
    # ### end Alembic commands ###
